/**:
  ros__parameters:
    kalman:
      process_noise:
        theta: 0.001
        x: 0.001
        y: 0.001
      sensor_noise: 0.1
    clusters:
      visualize: true
      threshold: 0.1 # m
    circles:
      visualize: true
      classification:
        mean_min: 90.0 # deg
        mean_max: 135.0 # deg
        std_dev_max: 8.6 # deg
      radius_min: 0.0 #0.01 # m TODO fix
      radius_max: 100000000.0 #0.1 # m TODO fix
    mahalanobis:
      threshold: 1.0 # m