/**:
  ros__parameters:
    kalman:
      process_noise:
        theta: 0.001
        x: 0.001
        y: 0.001
      sensor_noise: 0.1
    clusters:
      visualize: true
      threshold: 0.1 # m
    circles:
      visualize: true
      radius_min: 0.01
      radius_max: 0.1