/**:
  ros__parameters:
    rate: 200.0 # hz
    x0: 0.0 # m
    y0: 0.0 # m
    theta0: 0.0 # rad
    obstacles:
      x: [-0.35, -0.24, 0.38, 0.49, 0.28, -0.93] # m
      y: [0.8, 0.45, -0.7, -0.42, 0.10, 0.29] # m
      r: 0.038 # m
    input_noise: 0.025 # rad/s
    slip_fraction: 0.25
    basic_sensor_variance: 0.01 # m
    max_range: 0.5 # m
    lidar:
      resolution: 0.01 #m
      noise: 0.01 #m